name: CICD
on:
    workflow-dispatch:

jobs:
    # every jobs needs separate runner , it is a called parellelism
    code:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              run: echo "Code clone from github"

    build:
        needs: [code]
        runs-on: ubuntu-latest
        steps:
            - name: build docker container
              run: echo "docker container build"

    test:
        needs : [build]
        runs-on: ubuntu-latest
        steps:
            - name: test docker container
              run: echo "Testing the container"
    deploy:
        needs : [build,test]
        runs-on: ubuntu-latest
        steps:
            - name: Deploying the app
              run: echo "docker compose deployed the app"