name: CICD
on:
    workflow-dispatch:

jobs:
    code:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              run: echo "Code clone from github"

    build:
        runs-on: ubuntu-latest
        steps:
            - name: build docker container
              run: echo "docker container build"

    test:
        runs-on: ubuntu-latest
        steps:
            - name: test docker container
              run: echo "docker container exec."
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploying the app
              run: echo "docker compose deployed the app"